
GET http://localhost:3000/posts

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "StrongPassword123!",
  "firstname": "Jane",
  "lastname": "Doe",
  "locationAddress": "123 Main St"
}