
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "email": "franklin.doe@example.com",
  "password": "StrongPassword123#",
  "firstname": "Jane",
  "lastname": "Doe",
  "locationAddress": "123 Main St"
}